services:
  dev:
    image: yrobotics/y_boat_core:dev-local
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/dockerfile.dev
    command: sleep infinity
    volumes: !override
      - .:/workspace
      - /dev:/dev