ARG BASE_IMAGE=ros:jazzy-ros-base

FROM ${BASE_IMAGE}


ARG WORKSPACE=/workspace
ENV ROS_DISTRO=jazzy
ENV ROS_SOURCE=/opt/ros/jazzy/setup.bash
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-pip \
    udev \
    ros-${ROS_DISTRO}-navigation2 \
    ros-${ROS_DISTRO}-nav2-bringup \
    ros-${ROS_DISTRO}-foxglove-bridge \
    ros-${ROS_DISTRO}-vision-msgs \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR ${WORKSPACE}

COPY .docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN echo 'source ${ROS_SOURCE}' >> /root/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]