FROM dustynv/ros:humble-ros-base-l4t-r32.7.1


ARG WORKSPACE=/workspace

ENV ROS_DISTRO=humble
ENV ROS_SOURCE=/opt/ros/humble/install/setup.bash
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -o Acquire::AllowInsecureRepositories=true || true && \
    apt-get install -y --no-install-recommends curl ca-certificates gnupg && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu bionic main" > /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libpcap-dev \
    libpcl-dev \
    python3-colcon-common-extensions \
    python3-pip \
    udev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR ${WORKSPACE}


COPY .docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN echo 'source ${ROS_SOURCE}' >> /root/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
