name: Docker CI

on:
    pull_request:
        paths:
            - '.docker/**'
            - 'docker-compose.yml'

concurrency:
  group: docker-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
    build-docker:
        name: Test Docker + Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build dev image
              run:     docker build -t yrobotics/y_boat_core:github-ci -f ./.docker/dockerfile.dev .
